networks:
  roboshop:
    driver: bridge

services:
  mongodb:
    image: mongodb:v1
    build: ./mongodb
    container_name: mongodb
    networks:
      - roboshop

  catalogue:
    image: catalogue:v1
    build: ./catalogue
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb

  redis:
    image: redis
    container_name: redis
    networks:
      - roboshop

  user:
    image: user:v1
    build: ./user
    container_name: user
    networks:
      - roboshop
    depends_on:
      - mongodb
      - redis

  cart:
    image: cart:v1
    build: ./cart
    container_name: cart
    networks:
      - roboshop
    depends_on:
      - catalogue
      - redis

  mysql:
    image: mysql:v1
    build: ./mysql
    container_name: mysql
    networks:
      - roboshop

  shipping:
    image: shipping:v1
    build: ./shipping
    container_name: shipping
    networks:
      - roboshop
    depends_on:
      - mysql
      - cart

  web:
    image: web:v1
    build: ./web
    container_name: web
    networks:
      - roboshop
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - shipping